/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bamisu.log.gamethrift.entities;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-07-05")
public class TChangeUserMoneyObj implements org.apache.thrift.TBase<TChangeUserMoneyObj, TChangeUserMoneyObj._Fields>, java.io.Serializable, Cloneable, Comparable<TChangeUserMoneyObj> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TChangeUserMoneyObj");

  private static final org.apache.thrift.protocol.TField UID_FIELD_DESC = new org.apache.thrift.protocol.TField("uid", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField MONEY_FIELD_DESC = new org.apache.thrift.protocol.TField("money", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField MTYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("mtype", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField RE_FIELD_DESC = new org.apache.thrift.protocol.TField("re", org.apache.thrift.protocol.TType.I16, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TChangeUserMoneyObjStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TChangeUserMoneyObjTupleSchemeFactory();

  public long uid; // required
  public long money; // required
  public int mtype; // required
  public short re; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UID((short)1, "uid"),
    MONEY((short)2, "money"),
    MTYPE((short)3, "mtype"),
    RE((short)4, "re");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UID
          return UID;
        case 2: // MONEY
          return MONEY;
        case 3: // MTYPE
          return MTYPE;
        case 4: // RE
          return RE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private static final int __MONEY_ISSET_ID = 1;
  private static final int __MTYPE_ISSET_ID = 2;
  private static final int __RE_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UID, new org.apache.thrift.meta_data.FieldMetaData("uid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.MONEY, new org.apache.thrift.meta_data.FieldMetaData("money", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.MTYPE, new org.apache.thrift.meta_data.FieldMetaData("mtype", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.RE, new org.apache.thrift.meta_data.FieldMetaData("re", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16        , "short")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TChangeUserMoneyObj.class, metaDataMap);
  }

  public TChangeUserMoneyObj() {
  }

  public TChangeUserMoneyObj(
    long uid,
    long money,
    int mtype,
    short re)
  {
    this();
    this.uid = uid;
    setUidIsSet(true);
    this.money = money;
    setMoneyIsSet(true);
    this.mtype = mtype;
    setMtypeIsSet(true);
    this.re = re;
    setReIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TChangeUserMoneyObj(TChangeUserMoneyObj other) {
    __isset_bitfield = other.__isset_bitfield;
    this.uid = other.uid;
    this.money = other.money;
    this.mtype = other.mtype;
    this.re = other.re;
  }

  public TChangeUserMoneyObj deepCopy() {
    return new TChangeUserMoneyObj(this);
  }

  @Override
  public void clear() {
    setUidIsSet(false);
    this.uid = 0;
    setMoneyIsSet(false);
    this.money = 0;
    setMtypeIsSet(false);
    this.mtype = 0;
    setReIsSet(false);
    this.re = 0;
  }

  public long getUid() {
    return this.uid;
  }

  public TChangeUserMoneyObj setUid(long uid) {
    this.uid = uid;
    setUidIsSet(true);
    return this;
  }

  public void unsetUid() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UID_ISSET_ID);
  }

  /** Returns true if field uid is set (has been assigned a value) and false otherwise */
  public boolean isSetUid() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UID_ISSET_ID);
  }

  public void setUidIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UID_ISSET_ID, value);
  }

  public long getMoney() {
    return this.money;
  }

  public TChangeUserMoneyObj setMoney(long money) {
    this.money = money;
    setMoneyIsSet(true);
    return this;
  }

  public void unsetMoney() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MONEY_ISSET_ID);
  }

  /** Returns true if field money is set (has been assigned a value) and false otherwise */
  public boolean isSetMoney() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MONEY_ISSET_ID);
  }

  public void setMoneyIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MONEY_ISSET_ID, value);
  }

  public int getMtype() {
    return this.mtype;
  }

  public TChangeUserMoneyObj setMtype(int mtype) {
    this.mtype = mtype;
    setMtypeIsSet(true);
    return this;
  }

  public void unsetMtype() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MTYPE_ISSET_ID);
  }

  /** Returns true if field mtype is set (has been assigned a value) and false otherwise */
  public boolean isSetMtype() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MTYPE_ISSET_ID);
  }

  public void setMtypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MTYPE_ISSET_ID, value);
  }

  public short getRe() {
    return this.re;
  }

  public TChangeUserMoneyObj setRe(short re) {
    this.re = re;
    setReIsSet(true);
    return this;
  }

  public void unsetRe() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RE_ISSET_ID);
  }

  /** Returns true if field re is set (has been assigned a value) and false otherwise */
  public boolean isSetRe() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RE_ISSET_ID);
  }

  public void setReIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UID:
      if (value == null) {
        unsetUid();
      } else {
        setUid((Long)value);
      }
      break;

    case MONEY:
      if (value == null) {
        unsetMoney();
      } else {
        setMoney((Long)value);
      }
      break;

    case MTYPE:
      if (value == null) {
        unsetMtype();
      } else {
        setMtype((Integer)value);
      }
      break;

    case RE:
      if (value == null) {
        unsetRe();
      } else {
        setRe((Short)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UID:
      return getUid();

    case MONEY:
      return getMoney();

    case MTYPE:
      return getMtype();

    case RE:
      return getRe();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case UID:
      return isSetUid();
    case MONEY:
      return isSetMoney();
    case MTYPE:
      return isSetMtype();
    case RE:
      return isSetRe();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TChangeUserMoneyObj)
      return this.equals((TChangeUserMoneyObj)that);
    return false;
  }

  public boolean equals(TChangeUserMoneyObj that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_money = true;
    boolean that_present_money = true;
    if (this_present_money || that_present_money) {
      if (!(this_present_money && that_present_money))
        return false;
      if (this.money != that.money)
        return false;
    }

    boolean this_present_mtype = true;
    boolean that_present_mtype = true;
    if (this_present_mtype || that_present_mtype) {
      if (!(this_present_mtype && that_present_mtype))
        return false;
      if (this.mtype != that.mtype)
        return false;
    }

    boolean this_present_re = true;
    boolean that_present_re = true;
    if (this_present_re || that_present_re) {
      if (!(this_present_re && that_present_re))
        return false;
      if (this.re != that.re)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(uid);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(money);

    hashCode = hashCode * 8191 + mtype;

    hashCode = hashCode * 8191 + re;

    return hashCode;
  }

  @Override
  public int compareTo(TChangeUserMoneyObj other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUid()).compareTo(other.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uid, other.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMoney()).compareTo(other.isSetMoney());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMoney()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.money, other.money);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMtype()).compareTo(other.isSetMtype());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMtype()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mtype, other.mtype);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRe()).compareTo(other.isSetRe());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRe()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.re, other.re);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TChangeUserMoneyObj(");
    boolean first = true;

    sb.append("uid:");
    sb.append(this.uid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("money:");
    sb.append(this.money);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mtype:");
    sb.append(this.mtype);
    first = false;
    if (!first) sb.append(", ");
    sb.append("re:");
    sb.append(this.re);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TChangeUserMoneyObjStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TChangeUserMoneyObjStandardScheme getScheme() {
      return new TChangeUserMoneyObjStandardScheme();
    }
  }

  private static class TChangeUserMoneyObjStandardScheme extends org.apache.thrift.scheme.StandardScheme<TChangeUserMoneyObj> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TChangeUserMoneyObj struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // UID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.uid = iprot.readI64();
              struct.setUidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MONEY
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.money = iprot.readI64();
              struct.setMoneyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MTYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.mtype = iprot.readI32();
              struct.setMtypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // RE
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.re = iprot.readI16();
              struct.setReIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TChangeUserMoneyObj struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(UID_FIELD_DESC);
      oprot.writeI64(struct.uid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MONEY_FIELD_DESC);
      oprot.writeI64(struct.money);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(MTYPE_FIELD_DESC);
      oprot.writeI32(struct.mtype);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RE_FIELD_DESC);
      oprot.writeI16(struct.re);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TChangeUserMoneyObjTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TChangeUserMoneyObjTupleScheme getScheme() {
      return new TChangeUserMoneyObjTupleScheme();
    }
  }

  private static class TChangeUserMoneyObjTupleScheme extends org.apache.thrift.scheme.TupleScheme<TChangeUserMoneyObj> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TChangeUserMoneyObj struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetUid()) {
        optionals.set(0);
      }
      if (struct.isSetMoney()) {
        optionals.set(1);
      }
      if (struct.isSetMtype()) {
        optionals.set(2);
      }
      if (struct.isSetRe()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetUid()) {
        oprot.writeI64(struct.uid);
      }
      if (struct.isSetMoney()) {
        oprot.writeI64(struct.money);
      }
      if (struct.isSetMtype()) {
        oprot.writeI32(struct.mtype);
      }
      if (struct.isSetRe()) {
        oprot.writeI16(struct.re);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TChangeUserMoneyObj struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.uid = iprot.readI64();
        struct.setUidIsSet(true);
      }
      if (incoming.get(1)) {
        struct.money = iprot.readI64();
        struct.setMoneyIsSet(true);
      }
      if (incoming.get(2)) {
        struct.mtype = iprot.readI32();
        struct.setMtypeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.re = iprot.readI16();
        struct.setReIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

